<a href="https://colab.research.google.com/github/syauqidamario/thesis-MTI-syauqi/blob/main/01_data_berita.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pygooglenews pandas tqdm
from pygooglenews import GoogleNews
import pandas as pd
from datetime import datetime, timedelta
from tqdm import tqdm # Untuk melihat progress bar
import time

gn = GoogleNews(lang='id', country='ID')

Collecting pygooglenews
  Downloading pygooglenews-0.1.3-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.67.3)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from pygooglenews) (4.13.5)
Collecting dateparser<2.0.0,>=1.1.1 (from pygooglenews)
  Downloading dateparser-1.4.0-py3-none-any.whl.metadata (31 kB)
Collecting feedparser<7.0.0,>=6.0.8 (from pygooglenews)
  Downloading feedparser-6.0.12-py3-none-any.whl.metadata (2.7 kB)
Requirement already satisfied: requests<3.0.0,>=2.28.1 in /usr/local/lib/python3.12/dist-packages (from pygooglenews) (2.32.4)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.11.1->pygooglenews) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4<5.0.0,>=4.11.1->pygooglenews) (4.15.0)
Requirement already satisfied: regex>=2024.9.11 in /usr/local/lib/python3.12/dist-packages (from dateparser<2.0.0,>=1.1.1->pygooglenews) (2025.11.3)
Requirement already satisfied: tzlocal>=0.2 in /usr/local/lib/python3.12/dist-packages (from dateparser<2.0.0,>=1.1.1->pygooglenews) (5.3.1)
Collecting sgmllib3k (from feedparser<7.0.0,>=6.0.8->pygooglenews)
  Downloading sgmllib3k-1.0.0.tar.gz (5.8 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->pygooglenews) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->pygooglenews) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->pygooglenews) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.28.1->pygooglenews) (2026.4.22)
Downloading pygooglenews-0.1.3-py3-none-any.whl (10 kB)
Downloading dateparser-1.4.0-py3-none-any.whl (300 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 300.4/300.4 kB 8.7 MB/s eta 0:00:00
Downloading feedparser-6.0.12-py3-none-any.whl (81 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.5/81.5 kB 2.9 MB/s eta 0:00:00
Building wheels for collected packages: sgmllib3k
  Building wheel for sgmllib3k (setup.py) ... done
  Created wheel for sgmllib3k: filename=sgmllib3k-1.0.0-py3-none-any.whl size=6046 sha256=e9452feb83be4e2afe2efd9310ecc791171c5d3efe1f3bc5280b69d263ea988a
  Stored in directory: /root/.cache/pip/wheels/03/f5/1a/23761066dac1d0e8e683e5fdb27e12de53209d05a4a37e6246
Successfully built sgmllib3k
Installing collected packages: sgmllib3k, feedparser, dateparser, pygooglenews
Successfully installed dateparser-1.4.0 feedparser-6.0.12 pygooglenews-0.1.3 sgmllib3k-1.0.0

In [2]:
# Membuat daftar rentang tanggal bulanan dari 2020 sampai 2025
start_date = datetime(2020, 1, 1)
end_date = datetime(2025, 12, 31)

def generate_monthly_intervals(start, end):
    intervals = []
    current = start
    while current < end:
        next_month = (current.replace(day=28) + timedelta(days=4)).replace(day=1)
        intervals.append((current.strftime('%Y-%m-%d'), next_month.strftime('%Y-%m-%d')))
        current = next_month
    return intervals

intervals = generate_monthly_intervals(start_date, end_date)

In [3]:
# Scraping berita
all_news = []

for start, end in tqdm(intervals, desc="Scraping Berita"):
    query = f'"BBCA" saham after:{start} before:{end}'
    search = gn.search(query)

    for entry in search['entries']:
        all_news.append({
            'raw_date': entry.published,
            'title': entry.title,
            'source': entry.source.get('title'),
            'link': entry.link
        })
    # Beri jeda sedikit agar tidak dianggap bot oleh Google
    time.sleep(1)

df_raw = pd.DataFrame(all_news)

Scraping Berita: 100%|██████████| 72/72 [01:32<00:00,  1.28s/it]

In [4]:
# menampilkan data
df_raw.head(5)

,raw_date,title,source,link
0,"Wed, 15 Jan 2020 08:00:00 GMT",Harga Saham BCA Cetak Rekor Baru - CNBC Indonesia,CNBC Indonesia,https://news.google.com/rss/articles/CBMimgFBV...
1,"Sat, 18 Jan 2020 08:00:00 GMT","Top, Saham BBRI Catat Rekor Tertinggi di Tahun...",Ajaib,https://news.google.com/rss/articles/CBMijAFBV...
2,"Wed, 01 Jan 2020 08:00:00 GMT",Saham-saham yang Paling Untung dan Buntung Sep...,Katadata.co.id,https://news.google.com/rss/articles/CBMirwFBV...
3,"Thu, 20 Feb 2020 08:00:00 GMT","Laba BCA 2019 Tembus Rp 28,6 T, Melesat 11% - ...",CNBC Indonesia,https://news.google.com/rss/articles/CBMipAFBV...
4,"Fri, 21 Feb 2020 08:00:00 GMT",Bursa Sore: IHSG Dan Rupiah Sama-sama Tergelin...,Indo Premier Sekuritas,https://news.google.com/rss/articles/CBMiyAJBV...

In [5]:
def clean_news_title(text):
    # Menghapus nama sumber berita
    if ' - ' in text:
        text = text.rsplit(' - ', 1)[0]
    # Lowercase
    text = text.lower()
    # Menghapus karakter non-alfanumeric
    import re
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    return text.strip()

df_raw['cleaned_title'] = df_raw['title'].apply(clean_news_title)
df_raw['cleaned_title'].head(5)

0                     harga saham bca cetak rekor baru
1    top saham bbri catat rekor tertinggi di tahun ...
2    sahamsaham yang paling untung dan buntung sepa...
3             laba bca 2019 tembus rp 286 t melesat 11
4      bursa sore ihsg dan rupiah samasama tergelincir
Name: cleaned_title, dtype: object

In [6]:
# menyelaraskan waktu dan akumulasi akhir pekan

# Konversi ke format datetime
df_raw['Date'] = pd.to_datetime(df_raw['raw_date']).dt.tz_localize(None)

def adjust_to_trading_day(date):
    # 5 = Sabtu, 6 = Minggu
    if date.weekday() == 5: # Sabtu
        return (date + timedelta(days=2)).date()
    elif date.weekday() == 6: # Minggu
        return (date + timedelta(days=1)).date()
    else:
        return date.date()

df_raw['trading_date'] = df_raw['Date'].apply(adjust_to_trading_day)
df_raw['trading_date'].head(5)

0    2020-01-15
1    2020-01-20
2    2020-01-01
3    2020-02-20
4    2020-02-21
Name: trading_date, dtype: object

In [7]:
# agregasi harian (finalisasi dataset)
# Menggabungkan berita per tanggal perdagangan
df_final = df_raw.groupby('trading_date').agg({
    'cleaned_title': lambda x: ' [SEP] '.join(x), # Gunakan pemisah [SEP]
    'link': 'count'
}).reset_index()

df_final.columns = ['date', 'aggregated_news', 'news_count']

# Simpan hasil untuk Notebook 02
df_final.to_csv('01_berita_bbca_prepared.csv', index=False)